### ISSUE TITLE
Footer Widget Newline

### ISSUE THREAD

**Issue by kevensen** [RedHatGov/redhatgov.github.io#104]
I really like the footer widget.  It makes the labs more seamless when the user is inputing data.

I noticed after the **{{< span "userid" "YOUR#">}}**  it looks like a newline is inserted.  If this statement is in the middle of a sentence, it breaks it up.  Am I not using this right?

**Comment by kenmoini** [comment]
Are you talking about the newline inserted in some of the code boxes, such as this one...
![image](https://user-images.githubusercontent.com/1857778/41733839-c4643fac-754a-11e8-997d-7848b57384e4.png)
If so, that's not actually a new line, it's a CSS Style inherited from the parent Patternfly stylesheet.  It can be mitigated with the following...
```
pre code {
    white-space: initial;
}
```
