### ISSUE TITLE
Confusion about different workshops and domains

### ISSUE THREAD

**Issue by rndmh3ro** [RedHatGov/redhatgov.github.io#133]
Hi!

I'm trying to figure out what the best workshop-resources for teaching Ansible are.

So far I found:

* http://redhatgov.io/ -> Ansible Tower workshops
* http://ansible.redhatgov.io/ -> Multiple Ansible workshops, including tower
* http://ansible-workshop.redhatgov.io/ -> Ansible Essentials workshop, including tower
* https://github.com/ansible/lightbulb -> (community) resources from RedHat employees?

Finding all these left me with some questions:

* Why do both http://ansible.redhatgov.io/ and http://ansible-workshop.redhatgov.io/ exist? Isn't one (presumably the latter) redundant?
* Is the source for http://ansible.redhatgov.io/ and http://ansible-workshop.redhatgov.io/ available anywhere?
* Is there a need to have workshops from lightbulb and redhatgov? (I guess they were developed indepenently?)

Hope you can eliminate my confusion! :)

Thanks!

**Comment by dischord01** [comment]
Why do both http://ansible.redhatgov.io/ and http://ansible-workshop.redhatgov.io/ exist? Isn't one (presumably the latter) redundant?

Those sites are managed by the Ansible BU, they were supposed to migrate over to redhatgov.io.

Is the source for http://ansible.redhatgov.io/ and http://ansible-workshop.redhatgov.io/ available anywhere?

Check with @gdykeman

Is there a need to have workshops from lightbulb and redhatgov? (I guess they were developed indepenently?)

Lightbulb was developed by the Ansible BU and is an 8 hour class that focuses more on teaching Ansible language and has its own deployment scripts and dependencies for setting it up. The redhatgov site is a shorter 4hour workshop that is simple to set up, deploy, and tear down.

**Comment by rndmh3ro** [comment]
Thanks for clearing this up!

I found the source for the workshops on @gdykeman's profile.

Also I hope the Ansible BU team migrate the workshops so there's less confusion in the future. :)
