### ISSUE TITLE
Containers 101 - Ex 1.4 Command error

### ISSUE THREAD

**Issue by kenmoini** [RedHatGov/redhatgov.github.io#134]
'lo all...

Issue with the documentation for the Containers 101 workshop, Exercise 1.4 - Working with a Container Registry....
Last command...
`podman search --registry localhost:5000 postgresql`

There's no --registry option.  Proper format should be `podman search localhost:5000/postgresql`

See below

![issueswithpodman](https://user-images.githubusercontent.com/1857778/46046093-61768080-c0e5-11e8-9361-dc4aa801c425.png)

**Comment by dischord01** [comment]
Good catch, thanks!

**Comment by kenmoini** [comment]
Fixed by PR#135
