### ISSUE TITLE
Hugo binaries in repo don't indicate platform (i.e. linux vs mac)

### ISSUE THREAD

**Issue by jaredhocutt** [RedHatGov/redhatgov.github.io#168]
There is a `hugo` binary in the root of the repo that is compiled for macOS. The `hugo` binary in the `bin` directory is compiled for Linux.

These binaries should both be placed under the `bin` directory and renamed to indicate which is which.

For example:
- `<repo>/bin/hugo`
- `<repo>/bin/hugo-mac`

**NOTE:** If you change the name of `<repo>/bin/hugo`, this will break the TravisCI build unless you also update it to use the path of whatever the new filename is.

**Comment by jaredhocutt** [comment]
Thinking on this a bit more, a good way to solve this would be to use a containerized version of hugo and have a simple script that users can run that will map things correctly.

**Comment by dudash** [comment]
FYI - I just added /bin/hugo-mac64 but didn't change the name of the linux repo. This change will come in with the service mesh workshop PR - probably next week.

**Comment by kenmoini** [comment]
This can likely be closed now as well...Hugo binary has been versioned, updated, and symlinked for the different archs.

**Comment by ajacocks** [comment]
Closed.
