### ISSUE TITLE
Ansible Tower Workshop - STIG role name changed in Ansible Galaxy

### ISSUE THREAD

**Issue by ghylock** [RedHatGov/redhatgov.github.io#176]
The name of the role in Ansible Galaxy was changed. I found this when preparing for a workshop last week.

The change affect Lab3.

Old role name = rhel7_disa_stig
New role name = rhel7_stig

Until this is fixed you can change the role name in Lab3 Step 1 and fork the repo and modify role name in the main.yml file.

**Comment by matmille** [comment]
Migrated to Hardening profile rhel8-ospp
