### ISSUE TITLE
Location of example-network-playbook.yml in section 1.9?

### ISSUE THREAD

**Issue by tarexveff** [RedHatGov/redhatgov.github.io#251]
The instructions seem to instruct the user to simply "cat example-network-playbook.yml" but that does not exist in the user's home directory, nor can I find it in the roles directory.

**Comment by dthurston** [comment]
I found it... 
[ec2-user@ip-10-0-2-237 /]$ sudo find . -name example-network-playbook.yml -print
find: ‘./run/user/1000/gvfs’: Permission denied
./root/example-network-playbook.yml
I guess we need to update the instructions for it.

**Comment by ajacocks** [comment]
Closed by PR #91in redhatgov.workshops
