### ISSUE TITLE
podman generate kube command doesn't work. RHEL8 workshop, Exercise 1.8, Section 4, Step 4

### ISSUE THREAD

**Issue by dthurston** [RedHatGov/redhatgov.github.io#252]
Exercise 1.8, Section 4, Step 4 doesn't work for me:
[ec2-user@ip-10-0-2-237 ~]$ podman generate kube $(podman ps -l | awk '$0 ~ /Exited/ {print $1; exit}') > export.yaml
Error: no matching entries in passwd file

Varying ways to run this command still don't work (with sudo, with container ID, container name)

**Comment by dmc5179** [comment]
@dthurston I just ran this real quick and it worked for me. When you run through 1.4 section 3 and get to the step:
```
podman ps -l
```
does the Exited container id show? If you just run the subcommand after kube:
```
podman ps -l | awk '$0 ~ /Exited/ {print $1; exit}'
```
You should get the container id of the exited container. That is what I get.

**Comment by dthurston** [comment]
@dmc5179 Thanks for checking it.  I was able to generate the exited containers id using the above command.  If you can get it work correctly, then that's great.  I'm on RHEL 8.1 on my laptop (podman version 1.6.4) and was getting the error there as well... I just wanted to make sure it's not a problem during the lab.
