### ISSUE TITLE
The panel group shortcode doesn't allow more than one panel

### ISSUE THREAD

**Issue by jaredhocutt** [RedHatGov/redhatgov.github.io#26]
I retested the panel group function and it worked without issue.  I am uncertain what was wrong previously, however the following syntax works fine (shortened slightly for brevity)

```
{{< panel_group >}}
{{% panel "Web Console Steps" %}}

To expose via the web console, click on "Overview" to get to this view:

<img title="OpenShift Guest Book Application Overview" src="../images/ose-guestbook-noroute.png" width="600"/><br/>

<p>Notice there is no exposed route </p>

Click on the "Create Route" link

{{% /panel %}}
{{% panel "Alternatively: CLI Steps" %}}

<i class="fa fa-terminal"></i>In the command line type this:

``bash
oc expose service guestbook
``          

{{% /panel %}}
{{< /panel_group >}}
```

---

Original report by @jvanmeter

**Comment by jvanmeter** [comment]
@jaredhocutt Thank you for retesting.  I tested again and found no issue as well.  This might have been related to a format error elsewhere in the markdown document which was affecting the rendering.  Closing issue.
