### ISSUE TITLE
Image width not working

### ISSUE THREAD

**Issue by jaredhocutt** [RedHatGov/redhatgov.github.io#28]
One other note.  The image width value using the  following image reference syntax is being ignored.

```
{{< img title="OpenShift Console Login" src="../images/ose-login.png" width="600" >}}
```

The image is being loaded successfully, however the width is not being constrained to the value specified.  Should I use a different method of specifying the image width?

---

Original report by @jvanmeter

**Comment by jvanmeter** [comment]
This issue is specific to the width attribute is not be honored within panel groups.

**Comment by kenmoini** [comment]
In case this year old bug is still an issue, I'd suggest using the addition of `class="img-responsive"` and `style="max-width:600px"`

And if at all possible, use 'rem' instead of 'px' for sizing to account for variable DPI screens.
