### ISSUE TITLE
Alert box text does not allow bold or italics formatting

### ISSUE THREAD

**Issue by jvanmeter** [RedHatGov/redhatgov.github.io#34]
`{{< alert info >}} You can also arrive at this screen by clicking **Services** → **Requests**. {{< /alert >}}`

Is rendered as:

![image](https://user-images.githubusercontent.com/17306436/27233910-297ce2da-5289-11e7-945b-6e85d6ea183d.png)

**Comment by jaredhocutt** [comment]
When you use `{{< alert info >}}` that assumes that you have no markdown to render inside.

Instead, you need to use `{{% alert info %}}` (note the `%` instead of `<`) and it will render the markdown.
