### ISSUE TITLE
Images in wrong place for dcmetromap

### ISSUE THREAD

**Issue by dischord01** [RedHatGov/redhatgov.github.io#37]
Currently, the images are located in `redhatgov.github.io/content/static/openshift_101_dcmetromap`. 

They need to be located under `redhatgov.github.io/content/workshops/openshift_101_dcmetromap/images`

Please update the image location and point all image links to the new location.

**Comment by dudash** [comment]
will do - I'll probably leave this as-is until after we run through our workshop this week.

**Comment by jaredhocutt** [comment]
That is not a problem at all. My apologies for not catching it during the code review.

**Comment by jaredhocutt** [comment]
Fixed by #49
