### ISSUE TITLE
RHEL 8 AWS Lab: Exercise 1.7 oscap command can fail to generate report

### ISSUE THREAD

**Issue by benblasco** [RedHatGov/redhatgov.github.io#390]
Exercise 1.7 requires the user to generate reports using the following command:

`sudo oscap xccdf eval --fetch-remote-resources --profile xccdf_org.ssgproject.content_profile_ospp --results-arf /tmp/arf.xml --report /var/www/html/report.html /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml
`

It appears that in some cases the last line in the output of the command reads "Killed" and the report is not generated.

I have not been able to investigate the cause of the issue, but have found that it has been resolved by a reboot.  I have added a note in the lab instructions updated in my PR which can be found at: [https://github.com/RedHatGov/redhatgov.github.io/pull/389/commits](url)

**Comment by ajacocks** [comment]
Thanks, we’ll check that out, too.

**Comment by ajacocks** [comment]
I haven't been able to root-cause this, but since there is a documented work-around, we'll go with that. Closed by pr #389

**Comment by benblasco** [comment]
Hi Alex,

I believe the root cause is that the system runs out of memory.  Rebooting frees some memory, but adding some swap also solves this.  I will create a PR with my code to help with this.
