### ISSUE TITLE
Several minor issues with OpenShift 101 - DC Metro Map Workshop - Prereq, Lab 7 and Lab 8

### ISSUE THREAD

**Issue by gbenga-redhat** [RedHatGov/redhatgov.github.io#58]
Prerequisites - downloading git should be included. Quite a few of the attendees in a recent workshop working on Windows machines had issues when following the instruction for S2I
Lab 8 - We should change the name of the project to be created from "cicd" to "cicd-YOUR#" since projects in the cluster have a unique name (unless this is was done intentionally for the attendees to learn this lesson)
Lab 7 - There's a typo on the command to add a label. The quote in the piped grep command needs to be closed

**Comment by dischord01** [comment]
Added download link for git. Fixed Lab 8 cicd. Lab 7 works properly.
