### ISSUE TITLE
Update CI/CD Pipeline Lab in OpenShift 101 Workshop

### ISSUE THREAD

**Issue by dudash** [RedHatGov/redhatgov.github.io#84]
The lab content is based on a much older version of OpenShift before pipelines and Jenkins integration features.  

This might be a good source to use as a reference:
http://guides-roadshow.b9ad.pro-us-east-1.openshiftapps.com/index.html#/workshop/roadshow/module/continuous-delivery

**Comment by dischord01** [comment]
Thanks, that does make sense. I'll look at getting this updated.

**Comment by dudash** [comment]
closed by PR #107
